[toolchain]
# SBP-M2 review: nightly no longer required, provided update to more recent version
channel = "nightly-2023-05-22"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
