[toolchain]
# SBP-M2 review: nightly no longer required - https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.2.0
channel = "nightly-2023-05-22"
components = [
	"cargo",
	"clippy",
	"rust-analyzer",
	"rust-src",
	"rust-std",
	"rustc-dev",
	"rustc",
	"rustfmt",
]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
