[toolchain]
# SBP-M1 review: consider matching the Rust version used for the corresponding Substrate/Polkadot release used (see https://github.com/paritytech/polkadot/releases/tag/v0.9.43 for specifics)
channel = "nightly-2023-08-18"
components = [ "rustfmt" ]
targets = [ "wasm32-unknown-unknown" ]
